apiVersion: v1
kind: ServiceAccount
metadata:
  name: ferrum-mesh
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: ferrum-mesh
    app.kubernetes.io/instance: {{ .Release.Name }}
